name: ngrx-form-state
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Build affected projects
        run: npx nx affected:build --base=origin/master --head=HEAD

  lint:
    name: lint
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Lint affected projects
        run: npx nx affected:lint --base=origin/master --head=HEAD

      - run: npx nx format:check --base=origin/master --head=HEAD

  test:
    name: test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Test affected projects
        run: npx nx affected:test --base=origin/master --head=HEAD

  release:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    name: release
    needs:
      - build
      - test
      - lint
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Setup git user
        run: |
          git config --global user.name "Github Actions"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx nx release --skip-publish

      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: npx nx release publish
